sonar.projectKey=underpass-ai_underpass-runtime
sonar.organization=underpass-ai-swe-ai-fleet

sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage-full.out

sonar.coverage.minimum=70
sonar.newCode.coverage.minimum=80
