{{- if or (and (eq .Values.auth.mode "trusted_headers") (not .Values.auth.existingSecret)) (and (eq .Values.artifacts.backend "s3") (not .Values.artifacts.s3.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "underpass-runtime.fullname" . }}
  labels:
    {{- include "underpass-runtime.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
