{{- $tlsMode := include "underpass-runtime.tlsMode" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "underpass-runtime.fullname" . }}
  labels:
    {{- include "underpass-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if ne $tlsMode "disabled" }}https{{ else }}http{{ end }}
      protocol: TCP
      name: {{ if ne $tlsMode "disabled" }}https{{ else }}http{{ end }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "underpass-runtime.selectorLabels" . | nindent 4 }}
